### PR TITLE
Update GH Actions DR to 4.8

### PR DESCRIPTION
**Pull request by kfischer-okarin**

### CODE REVIEW

**Review by bedwardly-down — CHANGES_REQUESTED** [review]
You didn't update the artifact uploads. It'd be good to have them numbered with the version used so that when someone needs a specific release, it's readily available.

**Comment by kfischer-okarin** [comment]
I added it... but actually... I'm beginning to wonder if this PR makes sense at all as it is? 

Since it does just use headers and doesn't link against any shared objects or so at all... The build will in most cases (unless DR API changed or mruby was updated) not change at all....

The build can in most cases be the same... just the tests need to be run with different DR versions

**Comment by kfischer-okarin** [comment]
Let me retry this Pull request one more time later

**Comment by bedwardly-down** [comment]
> I added it... but actually... I'm beginning to wonder if this PR makes sense at all as it is?
> 
> Since it does just use headers and doesn't link against any shared objects or so at all... The build will in most cases (unless DR API changed or mruby was updated) not change at all....
> 
> The build can in most cases be the same... just the tests need to be run with different DR versions

That's a very good point and was something I thought about a couple days ago but didn't think to bring up.

**Pull request closed without merging**
